production:
  sessions:
    default:
      database: stor
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: stor_test
      hosts:
        - localhost:27017
      logger: false

development:
  sessions:
    default:
      database: stor_dev
      hosts:
        - localhost:27017